### PR TITLE
Interactions

### LINKED ISSUE #52: Interactions
Slash commands are still a bit of a pain to use, and they're *too* discoverable for admin commands...

We can start with using buttons though, such as join button for circles (easier to understand for new discord users) or approve buttons for mentor points system (more obvious and v small user base, but still could be nice)

Also, potentially put a button in the rules channel that users can click to approve, and then have a modal pop up. This takes away hassle of finding the approval channel. Issue with this is modals are extremely new rn, so maybe we should wait for that feature to mature a bit.

### PR DESCRIPTION
**Pull request by ez314**
PR to bring interactions support to the bot.
The commit history is unfortunately quite ugly, so please squash and merge. 

~~WIP PR to bring interactions support to the bot.~~

~~I'll be using this to track changes I make.~~

~~Please do not commit to this branch, since I will be re-doing commits and force pushing once I figure out the optimal structure.~~

Closes #52

### CODE REVIEW

**Comment by ez314** [comment]
As of right now, the bot registers 2 slash commands:
1. beep: basic ping, no args
2. admin: start of admin command suite, with user lookup. integrates with firebase lookup, implements arg options from discord, and has user-level permission control

**Comment by ez314** [comment]
Circles currently looks like the following:
image
image

**Comment by ez314** [comment]
Ok nevermind just going to squash and merge this :) 

These are the changes:
- Config file: added mod channel config
- Added interactions handlers for buttons, context menus, and slash commands
- Added interactions registration for context menu and slash commands
- Added multiple interaction-centric abstract classes to support organization. 
- Added report functionality, completely built on interactions for anonymity
- Migrated circle reaction roles to interactive buttons, with a framework for "Learn More" already set up (but not enabled). 
- Added admin slash command suite, currently with just one user lookup command. 
- Added "beep" slash command (which should probably replace the ping normal command)
- Consolidated dynamic source code loading to `util/dynamicloader`. This has been implemented in command, event, express, and interaction mangers. 

What's left:
Convert all the other commands to slash commands lmao

**Review by NickBurnett — APPROVED** [review]
🚀

**Pull request merged**
